version: '3.8'

services:
  ayupos-api:
    build:
      context: .
      dockerfile: AyuPos.Web.Api/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      # PostgreSQL connection string
      - ConnectionStrings__DefaultConnection=Host=db;Database=ayupos_db;Username=postgres;Password=YourPassword123!
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/swagger/index.html"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=ayupos_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YourPassword123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: